### ISSUE TITLE
Market.sol: get lot data function

### ISSUE THREAD

**Issue by ensrationis** [airalab/core#15]
@akru how I can view lot data without adding lot contract in watch contract? - probably no way :) Can you create function for viewing lot data with market or agent or regulator contract?

**Comment by akru** [comment]
In my opinion `MarketAgent` can do it.
But `Lot` is fully autonomous contract and have ABI for access its fields.

**Comment by ensrationis** [comment]
Ok, I added abi for lot in repo: https://github.com/airalab/core/blob/master/abi/modules/Lot.json  That will be enought for this release, but we need improve viewing lots list (create more user friendly UI)
