### ISSUE TITLE
Core.sol: removeModule problem

### ISSUE THREAD

**Issue by simonpavlov** [airalab/core#16]
"Aira BuilderDAO" in "DAO factory" at address "0xa76422591378d14fb6d94c9da48a42498d8b51da" create DAO in that romoveModule method not work.

**Comment by akru** [comment]
Hi, thank you for reporting! 
Please paste full code for test the problem on my side.

**Comment by akru** [comment]
This is **constant** module, it can not be removed by security reasons.

Please try again with new bin const module, and check by `isConstant` before try to removed.

**Comment by simonpavlov** [comment]
Understood. Thx for answer.
