### ISSUE TITLE
Aira core smart contract security

### ISSUE THREAD

**Issue by ensrationis** [airalab/core#17]
@akru я подготовил материал, на основе которого можно начать исследование вопроса: http://ensrationis.com/smart-contract-security/

**Comment by ensrationis** [comment]
Я изучил твой файл @akru , всё крайне не плохо написано/переведено и приведенный разбор контрактов неплох. Что предлагаю сейчас сделать:
- Переименуй Safe Solidity Draft в SecurityRegulations.md
- Внеси SecurityRegulations.md в корень Aira core репо

Дальше слово за мной...

**Comment by akru** [comment]
Добавил страницу в [wiki](https://github.com/airalab/core/wiki/Security-regulations), думаю, что это более подходящее место для большой статьи.

> wiki можно редактировать локально, это отдельный регозиторий, адрес: git@github.com:airalab/core.wiki.git
