### ISSUE TITLE
Scalable Market

### ISSUE THREAD

**Issue by akru** [airalab/core#19]
Current flat implementation of `Market` contract isn't scalable and have strong performance issues.
In my opinion is needed to prepare scalable market requirements and model.

**Comment by ensrationis** [comment]
Agree with you, it's very important issue for october release. You should start working with model on the next week and show me some draft of the model and after that we will to continue to improve together.

**Comment by akru** [comment]
Contract https://github.com/airalab/core/blob/develop/contracts/market/MarketHeap.sol ready.
It is base of self-sorting market lists: bids, asks; `log(n)` time to adding element into sorted list.

Markets should use it:
- https://github.com/airalab/core/blob/develop/contracts/market/Market.sol
- https://github.com/airalab/core/blob/develop/contracts/market/LiabilityMarket.sol
