### ISSUE TITLE
Getter for size of array

### ISSUE THREAD

**Issue by vol4tim** [airalab/core#23]
При работе с контрактом через web3js есть проблема с массивами.
Хорошо-бы добавить геттер, который будет возвращать размер массива.
Сейчас возникла проблема с массивом _group_ из контракта [ACLStorage.sol](https://github.com/airalab/core/blob/master/sol/acl/ACLStorage.sol)

**Comment by akru** [comment]
Добавил https://github.com/airalab/core/commit/133a147c2c079bf3831eb9f2bc88ca5019ef4ec0
