### ISSUE TITLE
The Blockchain Congress builder owner not is transaction sender

### ISSUE THREAD

**Issue by ensrationis** [airalab/core#26]
Desc: I was tried to use Congress builder twice with null in field _client and fill this field with my address, but owner and first congress member was "The Blockchain Congress builder " 

Builded contract example: `0xb9accd738d7b9ef0a04d2a4f24833f7a9b1b4e9e`
Type: The Blockchain Congress

**Comment by akru** [comment]
According to origin contract constructor:

```
if (congressLeader != 0) owner = congressLeader;
```

This seems like a leader should be an owner of Congress. Therefore builder isn't `delegate` to sender created Congress.

**Comment by ensrationis** [comment]
changeVotingRules(minimumQuorumForProposals, minutesForDebate, marginOfVotesForMajority);

        if (congressLeader != 0) owner = congressLeader;

        // It’s necessary to add an empty first member

        changeMembership(0, false, ''); 

        // and let's add the founder, to save a step later 

        changeMembership(owner, true, 'founder');
 Последние две строчки не могут быть исполнены, так как owner сменился.
 Работать это будет только если leader = sender

===============

Ok, change this section in contract and create new congress builder.

**Comment by ensrationis** [comment]
https://github.com/airalab/core/commit/a0e1a338943c7d97e91bae0f76078eb6ab1bf2f1
