### ISSUE TITLE
p2p random generator contract

### ISSUE THREAD

**Issue by noxonsu** [airalab/core#28]
необходимо имплементировать вот этот протокол https://github.com/Matchpool/contracts/blob/master/contracts/Contribution.sol 

Вкратце, что я понял:
1)игрок отправляет seed
2) держатель банкрола (не контракт) забирает seed из контракта
3) подписывает ее закрытым ключем (я проверил метод в JS ethUtil.ecsign из EthereumJS) и отправляет эту подпись обратно в контракт (и дополнительные данные r,s,v для валидации подписи)
4) контракт проверяет, что хеш прислал именно держателем банкрола, и что подписан именно seed клиента через функцию ecrecover 
5) собно полученный хеш пропускаем через uint(hash)%maxnum;  и получается число от 0 до maxnum. 

пример https://gist.github.com/noxonsu/82eff25bf0c537dce1a331b0b8863137

**Comment by EvgenRad81** [comment]
Removed to Dao.casino
