### ISSUE TITLE
option in withdrew function for onetime mint extra tokens

### ISSUE THREAD

**Issue by noxonsu** [airalab/core#29]
В функцию вывода добавить возможность сделать так, что бы при выводе генерировались и отправлялись на кошелек фонда дополнительные токены.  Например мы хотим 26% от общих выпущенных токенов отправить фонду. Значит выпускаем дополнительно totalsold/76*26

**Comment by akru** [comment]
Moved to https://github.com/airalab/dao.casino/issues/5
